### ISSUE TITLE
Environment-dependent errors when using non-ASCII characters

### ISSUE THREAD

**Issue by bluerayi** [acaos/python-pep505#2]
Hello.

In a Japanese Windows environment, the following parsing error occurs when attempting to execute source code containing non-ASCII (multibyte) characters.

```
> python -m main
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python310\lib\runpy.py", line 157, in _get_module_details
    code = loader.get_code(mod_name)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\parsinghook\hook.py", line 98, in get_code
    return FULLNAME_TO_LOADER[fullname]._parse_module()
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\parsinghook\hook.py", line 84, in _parse_module
    tree = self._parser.parse_module(f, self._filename)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\hook.py", line 52, in parse_module
    tree = parser.start()
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 60, in memoize_wrapper
    tree = method(self, *args)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\parser.py", line 405, in start
    (file := self.file())
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 60, in memoize_wrapper
    tree = method(self, *args)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\parser.py", line 416, in file
    (a := self.statements(),)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 60, in memoize_wrapper
    tree = method(self, *args)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\parser.py", line 489, in statements
    (a := self._loop1_3())
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 60, in memoize_wrapper
    tree = method(self, *args)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\parser.py", line 6463, in _loop1_3
    (statement := self.statement())
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 60, in memoize_wrapper
    tree = method(self, *args)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\parser.py", line 500, in statement
    (a := self.compound_stmt())
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 60, in memoize_wrapper
    tree = method(self, *args)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\parser.py", line 669, in compound_stmt
    self.positive_lookahead(self._tmp_7, )
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 250, in positive_lookahead
    ok = func(*args)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 60, in memoize_wrapper
    tree = method(self, *args)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\parser.py", line 6521, in _tmp_7
    (literal := self.expect('def'))
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 60, in memoize_wrapper
    tree = method(self, *args)
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\parser.py", line 230, in expect
    tok = self._tokenizer.peek()
  File "C:\Sandbox\sdvx_score_tool\venv\lib\site-packages\pep505\pegen\tokenizer.py", line 46, in peek
    tok = next(self._tokengen)
  File "<string>", line 452, in _tokenize
UnicodeDecodeError: 'cp932' codec can't decode byte 0x82 in position 998: illegal multibyte sequence
```

The source code file itself is written in UTF-8, but we think the reason is that Python on Japanese Windows tries to open the file in CP932 (SHIFT-JIS) by default.

I don't know much about the inner workings, but if you can solve this by explicitly specifying the encoding when opening the file, please do so.

Thanks.

**Comment by acaos** [comment]
Thank you for the report! I'm away at the moment but when I get back I will work on a fix (I'll be back within a week).

**Comment by acaos** [comment]
Notes to self: use `tokenize.open()` in https://github.com/acaos/python-parsinghook/blob/main/src/parsinghook/hook.py at:

```python
    def _parse_module(self):
        with open(self._filename, 'r') as f:
            tree = self._parser.parse_module(f, self._filename)
```

**Comment by acaos** [comment]
Since this was such a quick fix I managed to get it today. Please ensure the `parsinghook` dependency you have installed is version `0.9.1` or later:

- https://github.com/acaos/python-parsinghook/commit/436a723bcf96dc878f6759512ffa1c0c7e8787a0
- https://pypi.org/project/parsinghook/

(This should use the standard Python encoding detection by looking for a coding tag in the first two lines of the file)
